const messages: Record<string, string> = {
    invalid: "Sign-in could not be completed. Check your approved email and password.",
    unavailable: "Sign-in is temporarily unavailable. Please try again shortly.",
    limited: "Too many attempts. Please wait a few minutes before trying again.",
    session: "Please sign in again to open your private workspace.",
    signedout: "You are signed out. Your local history has not been erased."
};

export function recoveryDestination(value?: string): string | null {
    return value && /^https:\/\/[a-z0-9.-]+(?::\d+)?(?:\/[^<>"']*)?$/i.test(value) ? value : null;
}

export function loginPage(reason: string | null, configured: boolean, recoveryUrl?: string, mode: "login" | "recover" = "login"): Response {
    const recovery = recoveryDestination(recoveryUrl)?.replace(/&/g, "&amp;");
    const recovering = mode === "recover", ready = configured && (!recovering || Boolean(recovery));
    const recoveryMessages: Record<string, string> = {
        requested: "If this is your approved account, a recovery email has been requested. Check your inbox and spam folder, then open only the newest link. Email delivery may take a few minutes.",
        unavailable: "The recovery email could not be confirmed. Please try again shortly. Your password has not been changed.",
        limited: "Please wait before requesting another email. Check your inbox for the newest link already sent.",
        quota: "The email service has reached its sending limit. No new email was sent. Allow up to an hour before trying again; repeated requests will not help.",
        invalid: "Enter your approved account email address."
    };
    const message = !ready ? "Sign-in is being configured. Your financial workspace remains locked." : recovering ? recoveryMessages[reason || ""] || "You do not need to know your current password. This uses your existing account; it does not create another one." : messages[reason || ""] || "Use the same approved email and password as your Personal Life Assistant.";
    const form = `<form action="${recovering ? "/auth/recover" : "/auth/login"}" method="post"><label for="email">Email Address</label><input id="email" name="email" type="email" autocomplete="username" autocapitalize="none" spellcheck="false" maxlength="254" required ${ready ? "" : "disabled"}>${recovering ? "" : `<label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" maxlength="1024" required ${ready ? "" : "disabled"}>`}<button type="submit" ${ready ? "" : "disabled"}>${recovering ? "Send Recovery Email" : "Sign In"}</button></form>`;
    const guidance = recovering ? `<div class="privacy"><strong>What Happens Next</strong><ol><li>Open the newest recovery email.</li><li>The link opens Personal Life Assistant. Set your password there. If the dashboard appears, select <strong>Password</strong> in its status bar.</li><li>Return here and sign in with that same email and new password.</li></ol><p>The password is shared by both apps. Your saved Pocketview data is not cleared.</p>${recovery ? `<a class="recovery" href="${recovery}" target="_blank" rel="noopener noreferrer">Already Signed In To The Assistant? Open Password Settings There ↗</a>` : ""}</div><a class="recovery" href="/login">Back To Sign In</a>` : `<a class="recovery" href="/recover">Set Up A Password Or Recover Access</a>`;
    return new Response(`<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Sign In · Pocketview</title><style>
*{box-sizing:border-box}body{margin:0;background:#f6f5fb;color:#252d3c;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:16px;line-height:1.6}.loginShell{max-width:1120px;min-height:100dvh;margin:auto;padding:48px 28px;display:grid;grid-template-columns:1fr 460px;align-items:center;gap:72px}.brand{display:flex;align-items:center;gap:12px;font-weight:750;letter-spacing:-.02em}.mark{display:grid;place-items:center;width:38px;height:38px;background:#7764cd;color:white;border-radius:12px}h1{font-family:Georgia,serif;font-weight:400;font-size:clamp(2.5rem,5vw,4.5rem);line-height:1.1;letter-spacing:-.04em;margin:34px 0 24px}.intro p{max-width:340px;color:#657087}.loginCard{padding:34px;border:1px solid #d3dfd9;border-radius:20px;background:#fff;box-shadow:0 18px 60px #3234490b}.eyebrow{font-size:.8rem;font-weight:700;letter-spacing:.1em;color:#71639e}h2{font-size:1.8rem;line-height:1.25;letter-spacing:-.03em;margin:12px 0}.loginCard>p{color:#627086;margin:12px 0 24px}label{display:block;margin:18px 0 7px;font-size:.95rem;font-weight:600}input{display:block;width:100%;height:50px;padding:0 14px;border:1px solid #d7dce6;border-radius:10px;font:inherit;background:#fcfcff;color:inherit}input:focus-visible,button:focus-visible,a:focus-visible{outline:3px solid #b6a9eb;outline-offset:3px}button{width:100%;min-height:50px;margin-top:24px;border:0;border-radius:10px;background:#7563cc;color:#fff;font:inherit;font-weight:650;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}.recovery{display:block;margin-top:22px;color:#615299;text-underline-offset:4px;font-size:.95rem}.message{font-size:.95rem;line-height:1.6;background:#f4f2fb;border-radius:10px;padding:14px;margin-top:22px;color:#4d5569}.privacy{font-size:.875rem;color:#667183;border-top:1px solid #e6e9ef;margin-top:24px;padding-top:18px}.privacy summary{font-weight:600;cursor:pointer}.privacy p{margin-bottom:0}@media(max-width:900px){.loginShell{display:block;max-width:540px;padding:30px 20px}.intro h1,.intro p{display:none}.brand{margin-bottom:28px}.loginCard{padding:26px}}@media(max-width:380px){.loginShell{padding:22px 12px}.loginCard{padding:20px}}
</style></head><body><main class="loginShell"><section class="intro"><div class="brand"><span class="mark" aria-hidden="true">P</span>Pocketview</div><h1>Your money.<br>A clearer picture.</h1><p>One private place to understand your spending and build your budget.</p></section><section class="loginCard" aria-labelledby="login-heading"><span class="eyebrow">YOUR PERSONAL ACCOUNT</span><h2 id="login-heading">${recovering ? "Recover Your Access." : "Welcome To Pocketview."}</h2><p>${recovering ? "Set or reset the password shared by Pocketview and your Personal Life Assistant." : "Sign in with your Personal Life Assistant account."}</p>${form}<div class="message" role="status">${message}</div>${guidance}<details class="privacy"><summary>Your Privacy And Local History</summary><p>Only your approved account can open Pocketview. Passwords are checked by the same sign-in service as your Personal Life Assistant; Pocketview does not save them.</p><p>Your transaction history stays in this browser unless you export or publish it. Signing in on another device does not automatically transfer that history. Use an encrypted backup, and sign out on shared devices.</p></details></section></main></body></html>`, { status: ready ? 200 : 503, headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "private, no-store", "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'self'", "Referrer-Policy": "same-origin", "X-Content-Type-Options": "nosniff" } });
}
